[package]
name = "each"
version = "0.1.0"
authors = ["Arpad Ray <arraypad@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.33.0"
env_logger = "0.7.1"
failure = "0.1.6"
log = "0.4.0"
serde = "1.0.102"
serde_json = "1.0.41"
subprocess = "0.1.18"
