on:
  release:
    types: [created]

name: Release

jobs:
  release:
    name: release ${{ matrix.triple.target }}
    runs-on: ${{ matrix.triple.os }}
    strategy:
      fail-fast: false
      matrix:
        triple:
          - os: 'macOS-latest'
            target: 'x86_64-apple-darwin'
            cross: false
            ext: ""
          - os: 'ubuntu-latest'
            target: 'x86_64-unknown-linux-gnu'
            cross: false
            ext: ""
          - os: 'windows-latest'
            target: 'x86_64-pc-windows-msvc'
            cross: false
            ext: ".exe"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.triple.target }}
          override: true
      - name: build
        uses: actions-rs/cargo@v1
        with:
          command: build
          use-cross: ${{ matrix.triple.cross }}
          args: >
            --target ${{ matrix.triple.target }}
            --release
      - name: Compress binaries
        uses: svenstaro/upx-action@v2
        with:
          file: "target/${{ matrix.triple.target }}/release/each${{ matrix.triple.ext }}"
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: "${{ matrix.triple.target }}"
          path: "target/${{ matrix.triple.target }}/release/each${{ matrix.triple.ext }}"
